# fly.toml
app = "yoobee-clash-hub-api"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    restart_limit = 6
